[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.29.0"
checksum = "false"
ci = "github"
installers = []
pr-run-mode = "skip"
publish-jobs = []
source-tarball = false
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
unix-archive = ".zip"
