# Rustfmt configuration for asphalt
# Using only stable options for stable Rust toolchain

array_width = 60
attr_fn_like_width = 70
chain_width = 60
edition = "2024"
fn_call_width = 60
force_explicit_abi = true
hard_tabs = false
max_width = 100
merge_derives = true
newline_style = "Auto"
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50
struct_lit_width = 18
struct_variant_width = 35
style_edition = "2024"
tab_spaces = 4
use_field_init_shorthand = false
use_small_heuristics = "Default"
